#!/bin/bash
REPO_DIR=$(git rev-parse --show-toplevel)
DOT_GIT_DIR=$(git rev-parse --git-dir)
if [ "$DOT_GIT_DIR" = ".git" ]; then
	DOT_GIT_DIR="$REPO_DIR"/"$DOT_GIT_DIR"
fi
HOOKS_DIR="$DOT_GIT_DIR"/hooks
. "$HOOKS_DIR"/gitflow-functions

HOOK_ERROR=0
MESSAGE=$(cat $1)
LEN=$(echo ${#MESSAGE})

if [ $LEN -lt 8 ]; then
    echo "${CROSS}${RED} Such a short commit message? Give this commit a real meaning with a good commit message!${WHITE}"
    echo ""
    HOOK_ERROR=1
fi

exit $HOOK_ERROR