#!/bin/sh
#
# Runs before git flow hotfix finish
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
VERSION=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.
. "$HOOKS_DIR"/gitflow-functions
ROOTDIR=$(git rev-parse --show-toplevel)

gitflow_update_authors

gitflow_update_version $VERSION

# To terminate the git-flow action, return a non-zero exit code.
exit 0
